"""new fields in user model

Revision ID: 986e7f537575
Revises: e9d1efa1a964
Create Date: 2024-04-05 16:04:31.125932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e7f537575'
down_revision = 'e9d1efa1a964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
